import { describe,it,expect } from 'vitest';
import { GameModel } from '../src/systems/GameModel';
import { PlayerAnimationState,PLAYER_ANIMATIONS,playerAnimationFrame, type AnimationInput } from '../src/dev/playerAnimationState';
const input=(patch:Partial<AnimationInput>={}):AnimationInput=>({elapsed:1,hp:4,state:'playing',inBossArena:false,wallSide:0,player:{grounded:-1,vy:200,vx:0},...patch});
describe('candidate player animations',()=>{
 it('contains exactly the requested 35 frames and no thruster state',()=>{expect(Object.values(PLAYER_ANIMATIONS).reduce((n,a)=>n+a[0],0)).toBe(35);expect(Object.keys(PLAYER_ANIMATIONS)).not.toContain('boss_descend_thrust');});
 it('maps normal movement and wall contact',()=>{const s=new PlayerAnimationState();expect(s.pose(input())).toBe('fall');expect(s.pose(input({player:{grounded:-1,vy:-100,vx:0}}))).toBe('jump_rise');expect(s.pose(input({player:{grounded:1,vy:0,vx:0}}))).toBe('idle');expect(s.pose(input({player:{grounded:1,vy:0,vx:180}}))).toBe('run');expect(s.pose(input({wallSide:1}))).toBe('wall_contact');});
 it('requires a real shot for boss hover and does not map downward bounces',()=>{const s=new PlayerAnimationState();const m=input({inBossArena:true,player:{grounded:-1,vy:0,vx:0}});expect(s.pose(m)).toBe('boss_ascend');s.event({type:'empty'},m);expect(s.pose(m)).toBe('boss_ascend');s.event({type:'shot'},m);expect(s.pose(m)).toBe('boss_hover');expect(s.pose({...m,player:{...m.player,vy:-80}})).toBe('boss_brake');expect(s.pose({...m,player:{...m.player,vy:80}})).toBeNull();expect(s.pose({...m,elapsed:1.2})).toBe('boss_ascend');});
 it('keeps damage reaction shorter than invulnerability and uses airborne death',()=>{const s=new PlayerAnimationState();s.event({type:'hurt'},input());expect(s.pose(input())).toBe('damage');expect(s.pose(input({elapsed:1.2}))).toBe('fall');expect(s.pose(input({hp:0,state:'over'}))).toBe('death');});
 it('selects short event animations and resets timers',()=>{const s=new PlayerAnimationState();s.event({type:'shot'},input());expect(s.pose(input())).toBe('gunboots_fire');expect(s.pose(input({elapsed:1.2}))).toBe('gunboots_brake');s.event({type:'wallJump'},input());expect(s.pose(input())).toBe('wall_kick');s.reset();const m=input({player:{grounded:1,vy:0,vx:0}});s.event({type:'land'},m);expect(s.pose(m)).toBe('landing');});
 it('loops movement and holds final death frame',()=>{expect(playerAnimationFrame('run',.4)).toBe(0);expect(playerAnimationFrame('death',100)).toBe(3);});
 it('does not write to the model',()=>{const m=new GameModel();m.jumpToNimushi();m.step(1/60,0,false);m.shoot();const before=JSON.stringify(m),s=new PlayerAnimationState();for(const e of m.events)s.event(e,m);for(let i=0;i<100;i++)s.pose(m);expect(JSON.stringify(m)).toBe(before);});
});
